/****************************************************************************
 * Generated by tools/generate_kws_model_data.py. Do not edit manually.
 ****************************************************************************/

#ifndef __KWS_MODEL_DATA_H
#define __KWS_MODEL_DATA_H

#define R528_KWS_MODEL_EXPECTED_BYTES 65480
#define R528_KWS_FEATURE_FRAMES 178
#define R528_KWS_FEATURE_CHANNELS 40
#define R528_KWS_CATEGORY_COUNT 7
#define R528_KWS_BACKGROUND_INDEX 0
#define R528_KWS_UNKNOWN_INDEX 1
#define R528_KWS_HUMIDITY_INDEX 2
#define R528_KWS_LIGHT_INDEX 3
#define R528_KWS_AIR_QUALITY_INDEX 4
#define R528_KWS_TEMPERATURE_INDEX 5
#define R528_KWS_WAKE_INDEX 6
#define R528_KWS_HUMIDITY_THRESHOLD (50)
#define R528_KWS_LIGHT_THRESHOLD (-127)
#define R528_KWS_AIR_QUALITY_THRESHOLD (53)
#define R528_KWS_TEMPERATURE_THRESHOLD (82)
#define R528_KWS_WAKE_THRESHOLD (-127)

extern const unsigned char g_r528_kws_model_data[];
extern const unsigned int g_r528_kws_model_data_len;
extern const char g_r528_kws_model_sha256[];
extern const char g_r528_kws_evaluation_sha256[];

#endif /* __KWS_MODEL_DATA_H */
