############################################################################
# Contest 2026 team 113 ST7796 framebuffer test
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = st7796_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_CONTEST2026_113_ST7796_TEST)

MAINSRC = st7796_test_main.c

include $(APPDIR)/Application.mk
