#!/usr/bin/env python3
"""Generate checked C++ model data only from an accepted KWS evaluation."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import stat
import tempfile
from pathlib import Path

MODEL_LABELS = (
    "background",
    "unknown_speech",
    "query_humidity",
    "query_light",
    "query_air_quality",
    "query_temperature",
    "wake_nihao_vela",
)
INTENT_LABELS = MODEL_LABELS[2:]


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def read_regular(path: Path, maximum: int) -> bytes:
    info = path.lstat()
    if stat.S_ISLNK(info.st_mode) or not stat.S_ISREG(info.st_mode):
        raise ValueError(f"not a regular file: {path}")
    if info.st_size > maximum:
        raise ValueError(f"file is too large: {path}")
    return path.read_bytes()


def write_atomic(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as target:
            target.write(data)
            target.flush()
            os.fsync(target.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def load_json(path: Path, maximum: int) -> tuple[dict, bytes]:
    data = read_regular(path, maximum)
    try:
        value = json.loads(data.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ValueError(f"invalid JSON: {path}") from error
    if not isinstance(value, dict):
        raise ValueError(f"JSON root must be an object: {path}")
    return value, data


def checked_model(model_dir: Path) -> tuple[bytes, dict]:
    model_dir = model_dir.expanduser().resolve()
    if model_dir.is_symlink() or not model_dir.is_dir():
        raise ValueError("model directory must be a real directory")
    model = read_regular(model_dir / "kws_int8.tflite", 256 * 1024)
    evaluation, evaluation_data = load_json(
        model_dir / "evaluation.json", 2 * 1024 * 1024
    )
    acceptance, _ = load_json(model_dir / "MODEL_ACCEPTED.json", 64 * 1024)
    model_digest = sha256(model)
    if evaluation.get("schema_version") != 1 or evaluation.get("accepted") is not True:
        raise ValueError("evaluation did not accept this model")
    if evaluation.get("model", {}).get("sha256") != model_digest:
        raise ValueError("evaluation model SHA-256 mismatch")
    if evaluation.get("model", {}).get("bytes") != len(model):
        raise ValueError("evaluation model size mismatch")
    if acceptance.get("schema_version") != 1:
        raise ValueError("unsupported acceptance marker")
    if acceptance.get("model_sha256") != model_digest:
        raise ValueError("acceptance model SHA-256 mismatch")
    if acceptance.get("evaluation_sha256") != sha256(evaluation_data):
        raise ValueError("acceptance evaluation SHA-256 mismatch")
    threshold_entries = evaluation.get("thresholds", {}).get("by_label")
    if not isinstance(threshold_entries, dict):
        raise ValueError("accepted model thresholds are missing")
    thresholds = {}
    for label in INTENT_LABELS:
        entry = threshold_entries.get(label)
        threshold = entry.get("raw_int8") if isinstance(entry, dict) else None
        if not isinstance(threshold, int) or threshold < -128 or threshold > 128:
            raise ValueError(f"invalid threshold for {label}")
        thresholds[label] = threshold
    if acceptance.get("thresholds_raw_int8") != thresholds:
        raise ValueError("acceptance thresholds mismatch")
    quantization = evaluation.get("quantization", {})
    if (
        quantization.get("full_int8") is not True
        or quantization.get("frontend_input_identity") is not True
    ):
        raise ValueError("accepted model no longer satisfies INT8 input gates")
    model_labels = evaluation.get("model_labels")
    if model_labels != list(MODEL_LABELS):
        raise ValueError("accepted model label contract mismatch")
    return model, {
        "model_sha256": model_digest,
        "evaluation_sha256": sha256(evaluation_data),
        "thresholds": thresholds,
        "model_bytes": len(model),
        "category_count": len(model_labels),
        "indices": {
            label: model_labels.index(label) for label in MODEL_LABELS
        },
    }


def render_header(details: dict) -> bytes:
    return f"""/****************************************************************************
 * Generated by tools/generate_kws_model_data.py. Do not edit manually.
 ****************************************************************************/

#ifndef __KWS_MODEL_DATA_H
#define __KWS_MODEL_DATA_H

#define R528_KWS_MODEL_EXPECTED_BYTES {details['model_bytes']}
#define R528_KWS_FEATURE_FRAMES 178
#define R528_KWS_FEATURE_CHANNELS 40
#define R528_KWS_CATEGORY_COUNT {details['category_count']}
#define R528_KWS_BACKGROUND_INDEX {details['indices']['background']}
#define R528_KWS_UNKNOWN_INDEX {details['indices']['unknown_speech']}
#define R528_KWS_HUMIDITY_INDEX {details['indices']['query_humidity']}
#define R528_KWS_LIGHT_INDEX {details['indices']['query_light']}
#define R528_KWS_AIR_QUALITY_INDEX {details['indices']['query_air_quality']}
#define R528_KWS_TEMPERATURE_INDEX {details['indices']['query_temperature']}
#define R528_KWS_WAKE_INDEX {details['indices']['wake_nihao_vela']}
#define R528_KWS_HUMIDITY_THRESHOLD ({details['thresholds']['query_humidity']})
#define R528_KWS_LIGHT_THRESHOLD ({details['thresholds']['query_light']})
#define R528_KWS_AIR_QUALITY_THRESHOLD ({details['thresholds']['query_air_quality']})
#define R528_KWS_TEMPERATURE_THRESHOLD ({details['thresholds']['query_temperature']})
#define R528_KWS_WAKE_THRESHOLD ({details['thresholds']['wake_nihao_vela']})

extern const unsigned char g_r528_kws_model_data[];
extern const unsigned int g_r528_kws_model_data_len;
extern const char g_r528_kws_model_sha256[];
extern const char g_r528_kws_evaluation_sha256[];

#endif /* __KWS_MODEL_DATA_H */
""".encode("ascii")


def render_source(model: bytes, details: dict) -> bytes:
    rows = []
    for offset in range(0, len(model), 12):
        values = ", ".join(f"0x{value:02x}" for value in model[offset : offset + 12])
        rows.append(f"  {values},")
    body = "\n".join(rows)
    return f"""/****************************************************************************
 * Generated by tools/generate_kws_model_data.py. Do not edit manually.
 ****************************************************************************/

#include "kws_model_data.h"

alignas(16) const unsigned char g_r528_kws_model_data[] =
{{
{body}
}};

const unsigned int g_r528_kws_model_data_len =
  sizeof(g_r528_kws_model_data);
const char g_r528_kws_model_sha256[] =
  "{details['model_sha256']}";
const char g_r528_kws_evaluation_sha256[] =
  "{details['evaluation_sha256']}";
""".encode("ascii")


def generate(model_dir: Path, header: Path, source: Path) -> dict:
    model, details = checked_model(model_dir)
    write_atomic(header.expanduser().resolve(), render_header(details))
    write_atomic(source.expanduser().resolve(), render_source(model, details))
    return details


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("model_dir", type=Path)
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--source", type=Path, required=True)
    args = parser.parse_args()
    try:
        details = generate(args.model_dir, args.header, args.source)
    except (OSError, ValueError) as error:
        print(f"KWS 模型数组生成失败：{error}", file=os.sys.stderr)
        return 1
    print(json.dumps(details, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
